### ISSUE TITLE
Feature request: microsecond granularity timestamp

### ISSUE THREAD

**Issue by djarnis73** [osiegmar/logback-awslogs-json-encoder#5]
Logback only supports logging timestamp granularity of milliseconds, but you can log easily log multiple statements within the same millisecond which makes proper sorting problematic when searching the logs in aws logs insights.

I suggest a feature that will add a secondary timestamp field with micro or nanosecond precision to make sorting the log entries possible in logs insights.

It could be as simple as `.appendToJSON("timestampNano", System.nanoTime())` to `AwsJsonLogEncoder.encode`.

What do you think?

**Comment by osiegmar** [comment]
I don't want to extend this library itself with those 'special' fields. But it could be extended in a similar way as it happened with logback-gelf:

https://github.com/osiegmar/logback-gelf/blob/v4.0.2/src/main/java/de/siegmar/logbackgelf/GelfEncoder.java#L271

Unfortunately I don't have the time at the moment.

**Comment by osiegmar** [comment]
Closing this, as this library is going in archive mode now.
